sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5t9aLM8vUp3rjRA1J6V5
    accessKeySecret: HBaIu8MYxnsurUonWipRRKcEIdF6Iz
    bucketName: web-tliaszhang
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
